[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "0302cbf184548e791795b41fb2d21fedecf704d3"
lazy = true
mpi = "mpich"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "e5e162837a3563b7b56dbc50f1e188f8f51ce8f8f4f98c78d0e6aa97ce5c3f0b"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "9fe780fb2bcec2bd0598ce6b3541d4e7e39ff0eb"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "6fd1d70e580490430060130a4335f99b56f7ee3108fffb2be45c1cdb2f41f767"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "9e3d24f0e596e56f7e055b5fed676e67a40cd0fe"
lazy = true
mpi = "openmpi"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "cca96d7966d976e67746ee358f3e647ec6723e10d6d81726951c054d075af00b"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "6cae7b41e2fd61ffcd8fc34399ec5f0fd26cec69"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "4a752fd580bfcd67ab7584d11df9911410ce374af890ad6925f9f474f3fc5d23"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "23cfefd229d37acadeb31120d3e8f5e2417a553a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "4b05862728506e20bf253f90d3e361c78acfaabdae991d5d688fbb6768d1ad10"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "282fd71517cbad2fae8f9c42886726b48173a4fd"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "4ee4fa77464ffc4a38fac23251276cc4b430e721dcdc91460935dcf8790e5df7"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "746546992267107ab113e76a8f9dda1907f663a5"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "ea8fb543c2f479ac26ed7c483333930ce9789d3516ff7e56fdf13e753e46aebd"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-linux-musl-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "a7cf9bc8c1a2a49b3050080e56182cc5b52e03f0"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "007008896de176700f9e5940ccd7c6a1f123438e61b285d5743311fdeb36ba8c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "070b2169602b2b789cc0d4e91cebb8923c380eef"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "f7384a40d1155e6c6b117c574270edd862a81375bbe34ce81aa2b94e88f26220"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "710f2475be64512842237eb983598272f4c87a97"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "86f37a83a88ffeb6d31c07a8bf7f10954f32a725b6d49404e629e458206fee8c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c7cea0fb73666a5800ee1f41293f0ddacfa8599"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "38cf76fac7639259cbe2d90a156c6880111082197b82915f670506ab03fdecea"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f87db9b6227052e0d47d63a2c8e0e83fc8b57a3c"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "6ab1a781cba5de50a825502ae31427b2f2d55dcace63fb5568fd510f0ebf9673"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54c6c0af52d01f6351aa0aa576b375da2627f17d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "dc2a0c9f101962911686897d5e7839b787b02ae38628270325cc1d134f841cab"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ce059c3a48f4c18faf19406bfc983356f93e25e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "a8270b7d6b7ac7fe334d02b3e0410446ddb9407a42eb74dc1fa5210760b2d503"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1284f6e8a41c14403af6a1f970e08b5824218473"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "d0197a262d0177cae79d62e41099fa48b000c3c4ba53b7e1442e039ddeae554a"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "55e9a4acf4064e11d2b0fa0daef02d1763eb46b7"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "897d5f3698af768d6c0b55e1c21d12829d02d457a660dffe3a1a86ff4d8e326c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "220d41359edff716a1d5c0d6497083aabfdcf664"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "e9ef8d9e49c0caf2aced630b86de637795028565b89a98185966505c23a3668c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "15e89d65fb20f78120e9e2fb826ac25275735fb0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "345bc05ba07570916e68bf2092a26b8ac2f3e3af8d04988b7ec8f2d4a9b9d5f7"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.i686-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "8c3939b1f0c6d05fdeedcd53031acb9e605b341b"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "b5d76debf2384cfb6be5dd5eb1e5133ec10c54e8c6c6aae440705e566e6f963e"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "b2d4f086b606b493646f372b179c18f8ee49bf59"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "bd37cfcd20cf8b4700d2e193b5777b7d60787f636b5cb31580159eb920da7d45"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.i686-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "6918da4cebd8bf543b2f7c85ae43a02fbc2707c7"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "342500ac25d316a211c8a3c9db640acc6c6d873c4be78f1613e88af2a7e6cdfc"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.i686-linux-musl-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "b370cebc3a113bc3d0b456e3b3fd0bf1de56c768"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "8151cb7265c64db508d226d8a835f85cbdfb49ceffde2c25b9436a8993240c0d"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.i686-linux-musl-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "powerpc64le"
git-tree-sha1 = "26e5c718cc3cf6c70b5c10ba9e7dc6382bc36802"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "c530193c079eb6ede852cf62525214d5de27d264d59bace9fb2f6e86225592af"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "powerpc64le"
git-tree-sha1 = "9cb4743a9408dcbc5b6af937786b4e67776bf851"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "963c83bc0bede88ae817bf86e179d77090cca82a58cf8e845694a8b9d14e1c3c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "powerpc64le"
git-tree-sha1 = "198bbda8704c2055f0ec23fdc6bb4dbf3f654cdc"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "e471f26147de9820c948ff0ba741e0c19b59e08b06bacf3d9a8344a8550d1f3c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "2bb10ed4b0fdb18ba2ee7c606a4e375a3fdd515a"
lazy = true
mpi = "mpich"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "b0e5a334ee463040dde2782b8f985253470f6afbf76d39b5108011117eee8445"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "a9f8917cff529a15522a31a247e2f0e1fbfca608"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "6b19edc360379ef60436ee7baedd76452b15373c36b6f80f653c0a9ff2916eb9"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "fa2be3e3edc7b8a635df08a89975ce74a628388a"
lazy = true
mpi = "openmpi"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "3af0cde0fcd40e54c99cd806b4e8a5f02da325d593295e31c023344f76de59aa"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "f35532a296e26e2aa8dd3912debdba4b3f73446a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "55eadd87dde248f5bab1035a56eaff6b56cecdd05a4a967579d585a9ea2537aa"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "c12d83c6a8dc4a608f346e1243ac7114858de7cd"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "4f9744a7fadf809d9256dd530e3fd8f02a773a9ceaef889ec97c3118271bbb3b"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "aa808a360367759702ee6ead18556daf72f78f54"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "cc20b8cbe1e119352b838956e25cca43d8900176c7341d6de7638515d555f039"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "7a9c390c8f2725c03695e914e7ef55ccb7f10bbd"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "3f783aa4b863903ddc63423cbdb23992c0eea5ebac5ca8eb99618b6b9e4ee1da"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-linux-musl-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "40e96839e5aca8afccf05edc5afd263770b8c51c"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "253461c440ee3557d3ad46022a9798f70845ddde78e6724cf371c1a22a40c7da"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "1a1dc16609254ab2fb56df21d1aef2c31045470c"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[PARMETIS.download]]
    sha256 = "2f8692b2632594e78ba8e48d6210b9cf7fc79d0f0963e35b5c42cf3d3d925f2c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "31e490902a82be52088d819605111d10006562b5"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[PARMETIS.download]]
    sha256 = "8f00023fc43ddafa85699fbc9461d1add7f8ce2d8a6e213d6284e76bdc6bd1fc"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+0/PARMETIS.v4.0.6.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
