[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "623c01ac16157e3cf35311ab7953480e4489a0b8"
lazy = true
mpi = "mpich"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "02bda44eb2211226bb0045c0fdbb2b5d30965625189bfddbd3f4653ee45b2b4e"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "24abe94c2d601b24d6b01916c36c5c1d0d19dc5c"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "907ab6e07839620912e8b8aae6afa1dbbd548c8d21ff7d170ddbee69a6b8c8bb"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "6e8106e04ce6fa17303466f06f821f890cb31f7f"
lazy = true
mpi = "openmpi"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "bf546dc96c66a52512a7fc452be18a457ec9e8be4f53904a621964cc8016f7b2"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "6cae7b41e2fd61ffcd8fc34399ec5f0fd26cec69"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "4a752fd580bfcd67ab7584d11df9911410ce374af890ad6925f9f474f3fc5d23"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "67f64c8fa70cbdb6efa40bdd0e08f6bc6c716558"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "eedbe2a207487051309b7fbdb0d441d3715b3dd22990c81600a3321593310ae1"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "e76ad9f475f0bed2552ded1607d8b21e877bce4b"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "95175d37bd0d48aff5d5812f233f9626bccc773a1c6260a1559d5501de36ff37"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "0f81bf2c9c4829fee2acc099109457bc14b693bd"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "1ca6227f6a0f3227682031318d908138dfaf210f3ba44de37f1b1f7e2a623614"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-linux-musl-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "aarch64"
git-tree-sha1 = "a7cf9bc8c1a2a49b3050080e56182cc5b52e03f0"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "007008896de176700f9e5940ccd7c6a1f123438e61b285d5743311fdeb36ba8c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "383c79508a9e68108e151f698b7f5e1d40ffa135"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "fa8f2ae6c0a386ef85a769c4bb1f96d51d021265df88b50bd425b822e0b544db"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d582424d5461345d84685434e852a4cf4083067a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "3388499c4dd12fcbf1b6cb506de58aa1a9bf0dc202dce6bf30067bf31559e64e"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fd5a7cf0c7abf5e1fa3af4fa149f8036016b2c7c"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "035a05924b9e7667076234ef0c858a8d066ac390d941255ae2bb50409d0cfd43"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f87db9b6227052e0d47d63a2c8e0e83fc8b57a3c"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "6ab1a781cba5de50a825502ae31427b2f2d55dcace63fb5568fd510f0ebf9673"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54c6c0af52d01f6351aa0aa576b375da2627f17d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "dc2a0c9f101962911686897d5e7839b787b02ae38628270325cc1d134f841cab"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ce059c3a48f4c18faf19406bfc983356f93e25e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "a8270b7d6b7ac7fe334d02b3e0410446ddb9407a42eb74dc1fa5210760b2d503"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ccc97df26d66a1c53332374f502df63e006ae3d7"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "b00260a708849ab778e8e4813f70e978b0ad15b548e56184fc6d0c672474e353"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "918973cd8aad6ed647dee2c6b5d277ae50cc9ef0"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "97fab6c1226f8cacf7d537db3e6ea96db825c5b69af2761057073c19af8bad10"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "220d41359edff716a1d5c0d6497083aabfdcf664"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "e9ef8d9e49c0caf2aced630b86de637795028565b89a98185966505c23a3668c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "b48b232818243213c2498e5ffbac4db376cc2d8e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "20679ecaa179e79b36dd173b1a98ea3feccdc842bf49776ffedb914599b48f82"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.i686-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "d3de2f6713bb173a21366909ec0588c7951bec41"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "4f96133d6a0d587c8c565f93ad357076fe55cfde731b5873ccd979a5f8301f78"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "713c3d4095ced8654e5f9c090b9382752126b05d"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "8e0f2c6ad58abcc40f4a647f4e64c0e404594248d664be52d51376a0ef559a23"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.i686-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "877d3edb22d5e8e1a23a67c2e2b53ee32f724f9b"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "bcfc446779b1f03d41a1b895a322bed581b7c8296936e994b1feb7988fb60472"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.i686-linux-musl-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "0179c568b362048cc5d311995746a7c6d277b14c"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "402592a457fa86ac18653d7056e2d0ccb2fa52c199bb6cc969b798cebb9df76a"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.i686-linux-musl-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "i686"
git-tree-sha1 = "cfe65489ee7f9b1df12d1fb2e888d3c5f9a4f81d"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[PARMETIS.download]]
    sha256 = "b5d7a93c0775d8c1f0241f89ce7dc4f3cfb377e7cde6462ed1be2ef8be06d8ea"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.i686-w64-mingw32-mpi+microsoftmpi.tar.gz"
[[PARMETIS]]
arch = "powerpc64le"
git-tree-sha1 = "96f323a669ef2daa957782fc156000455aa41150"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "b34157061c3934df2dd0c23440ace9c08e49d45dd06790131620454432aa7219"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "powerpc64le"
git-tree-sha1 = "9cb4743a9408dcbc5b6af937786b4e67776bf851"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "963c83bc0bede88ae817bf86e179d77090cca82a58cf8e845694a8b9d14e1c3c"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "powerpc64le"
git-tree-sha1 = "0bc350f5134c8950be77f07a56eeca23a9d1af8b"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "8484519965b8c52e3d65ce1167823a74046420795bf0ab9ac2ca59efcb64adbc"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "3669a33addb12ac605503413f0ea6bfba770a1e2"
lazy = true
mpi = "mpich"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "9b1cbde60d2f01953cf5f097ccbef8790c1c7d1d38fe476ad38b013cb6427597"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "4d24d7125753859c4c2c0eb35cbf16054d231d8a"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "20e838132250a9e83cef0a922754af92f3068df2912d2d2a59744a32dfab1023"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "8ecda7fbe754c57bf29b89b35eee091484b3790d"
lazy = true
mpi = "openmpi"
os = "macos"

    [[PARMETIS.download]]
    sha256 = "0e97e339d323f1086902806a547186db57ec50d321393b1371d8d2eed66da2ed"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "f35532a296e26e2aa8dd3912debdba4b3f73446a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "55eadd87dde248f5bab1035a56eaff6b56cecdd05a4a967579d585a9ea2537aa"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "c12d83c6a8dc4a608f346e1243ac7114858de7cd"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "4f9744a7fadf809d9256dd530e3fd8f02a773a9ceaef889ec97c3118271bbb3b"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "589cca8ddf33cc8b409e10adf524651a973dd29d"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "b745890015e9dac5175914568cdf999e498962ac7f18ec0aa86fa518f1cb81de"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "e8414959e1b25fa1075eee79f891ab041c00643e"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "d57ff9790a8649effbcf2d1a3fef20832418ef6661a3639d7f834ce3e22b774b"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-linux-musl-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "40e96839e5aca8afccf05edc5afd263770b8c51c"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PARMETIS.download]]
    sha256 = "253461c440ee3557d3ad46022a9798f70845ddde78e6724cf371c1a22a40c7da"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "dd25f76f06f2369b227ee393529cfd06a8195bad"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[PARMETIS.download]]
    sha256 = "baee2920e1602df1b6ce02b14d11c199d9124eaa364e2a40b486c7c724a33e6f"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "31e490902a82be52088d819605111d10006562b5"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[PARMETIS.download]]
    sha256 = "8f00023fc43ddafa85699fbc9461d1add7f8ce2d8a6e213d6284e76bdc6bd1fc"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
[[PARMETIS]]
arch = "x86_64"
git-tree-sha1 = "b0c7cde3da8c6be9929ce13ad69eb8f23aca524f"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[PARMETIS.download]]
    sha256 = "14c5399f9428ab72bf4803035c3ef6dd050d207747677e838ea1a12679bd65ce"
    url = "https://github.com/JuliaBinaryWrappers/PARMETIS_jll.jl/releases/download/PARMETIS-v4.0.6+1/PARMETIS.v4.0.6.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
