# Autogenerated wrapper script for PARMETIS_jll for x86_64-apple-darwin-mpi+mpich
export libparmetis, libparmetis_Int32_Real64, libparmetis_Int64_Real32, libparmetis_Int64_Real64

using METIS_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("PARMETIS")
JLLWrappers.@declare_library_product(libparmetis, "@rpath/libparmetis.dylib")
JLLWrappers.@declare_library_product(libparmetis_Int32_Real64, "@rpath/libparmetis_Int32_Real64.dylib")
JLLWrappers.@declare_library_product(libparmetis_Int64_Real32, "@rpath/libparmetis_Int64_Real32.dylib")
JLLWrappers.@declare_library_product(libparmetis_Int64_Real64, "@rpath/libparmetis_Int64_Real64.dylib")
function __init__()
    JLLWrappers.@generate_init_header(METIS_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libparmetis,
        "lib/libparmetis.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libparmetis_Int32_Real64,
        "lib/libparmetis_Int32_Real64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libparmetis_Int64_Real32,
        "lib/libparmetis_Int64_Real32.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libparmetis_Int64_Real64,
        "lib/libparmetis_Int64_Real64.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
